on: 
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6.0.0

      - name: Docker Hub Login
        id: docker_login
        if: steps.checkout.outcome == 'success'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build and push
        if: steps.docker_login.outcome == 'success'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: vaozgeely/express-app:latest
  
  publish:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: needs.build_and_push.result == 'success'
    steps: 
      - name: Deploy
        uses: tiyee/action-ssh@v1.0.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }} 
          privateKey: ${{ secrets.VPS_PRIVATE_KEY }} 
          command: 'docker stop express || true && docker rm express || true && docker run --name express -e SECRET=${{secrets.APP_SECRET}} -d -p 3000:3000 --pull always vaozgeely/express-app:latest'

      